# Generated by Django 6.0.5 on 2026-05-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecklistitem',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='lenders.lenderprofile'),
        ),
    ]
