# Generated by Django 5.2.7 on 2025-12-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cblregistration',
            name='lender_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbl_registration', to='lenders.lenderprofile'),
        ),
    ]
