# Generated by Django 5.2.7 on 2025-12-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceprofile',
            name='lender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='lenders.lenderprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancechecklistitem',
            unique_together={('lender', 'requirement_key')},
        ),
    ]
