# Generated by Django 5.2.7 on 2025-12-11 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancechecklist',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='compliance.cblregistration'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='cbl_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.cblregistration'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='lender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='compliance.compliancedocument'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancechecklist',
            name='evidence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfies_requirements', to='compliance.compliancedocument'),
        ),
        migrations.AddField(
            model_name='keypersonnel',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_personnel', to='compliance.cblregistration'),
        ),
        migrations.AddField(
            model_name='keypersonnel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='key_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.keypersonnel'),
        ),
        migrations.AddField(
            model_name='ongoingcompliancereport',
            name='lender_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='ongoingcompliancereport',
            name='report_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_submissions', to='compliance.compliancedocument'),
        ),
        migrations.AddField(
            model_name='ongoingcompliancereport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='keypersonnel',
            unique_together={('registration', 'national_id')},
        ),
    ]
