# Generated by Django 5.2.7 on 2026-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceprofile',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceprofile',
            name='investigation_fee_proof',
            field=models.FileField(blank=True, help_text='Upload the bank transfer/deposit slip', null=True, upload_to='compliance/payments/'),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='doc_type',
            field=models.CharField(choices=[('schedule_i', 'Schedule I - License Application'), ('schedule_ii', 'Schedule II - Information Sheet'), ('business_plan', 'Business Plan'), ('audited_financials', 'Audited Financial Statements'), ('financial_statements_certified', 'Certified Financial Statements (Tier 3)'), ('capital_proof', 'Proof of Capital'), ('board_resolution', 'Board Resolution for Licensing'), ('memorandum_articles', 'Memorandum & Articles of Association'), ('tax_clearance_institution', 'Institution Tax Clearance'), ('risk_manual', 'Risk Management Manual'), ('aml_manual', 'AML/CFT Manual'), ('complaints_procedure', 'Consumer Complaints Procedure')], max_length=50),
        ),
    ]
