# Generated by Django 6.0.5 on 2026-09-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_remove_borrowerprofile_mobile_money_name_and_more'),
        ('lenders', '0004_remove_lenderprofile_mobile_money_name_and_more'),
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa (Vodacom)'), ('ecocash', 'EcoCash (Econet)'), ('cpay', 'C-Pay (Chaperone)')], max_length=20)),
                ('number', models.CharField(help_text='The number money is sent to.', max_length=20)),
                ('account_name', models.CharField(blank=True, help_text='Name registered on the mobile-money account.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to='borrowers.borrowerprofile')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to='lenders.lenderprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('borrower__isnull', False)), fields=('borrower', 'provider'), name='uniq_borrower_provider'), models.UniqueConstraint(condition=models.Q(('lender__isnull', False)), fields=('lender', 'provider'), name='uniq_lender_provider')],
            },
        ),
    ]
