# Generated by Django 6.0.5 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('test', 'Test mode (not sent)')], max_length=10),
        ),
    ]
