# Generated by Django 6.0.5 on 2026-08-10 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(default='home', max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['phone_number', 'ended'], name='comms_ussd__phone_n_530ac7_idx')],
            },
        ),
    ]
