# Generated by Django 6.0.5 on 2026-08-09 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('event_id', models.CharField(help_text="Provider's unique id for this callback.", max_length=128)),
                ('reference', models.CharField(blank=True, help_text='Our transaction reference, if present.', max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate (ignored)'), ('rejected', 'Rejected (bad signature)'), ('error', 'Error')], default='received', max_length=20)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'reference'], name='integration_provide_9902cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_provider_event')],
            },
        ),
    ]
