# Generated by Django 5.2.3 on 2025-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('loan_application', 'Loan Application'), ('loan_payment', 'Loan Payment'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_update', 'Loan Update'), ('document_update', 'Documents Updated'), ('loan_deleted', 'Loan Deleted')], default='loan_application', max_length=20),
        ),
    ]
