# Generated by Django 6.0.5 on 2026-08-06 14:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
        ('lenders', '0002_initial'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='current_stage',
            field=models.CharField(choices=[('employment_type', 'Employment Type'), ('documents', 'Upload Documents'), ('affordability', 'Affordability'), ('loan_calculator', 'Loan Calculator'), ('apply_loan', 'Apply Loan'), ('submitted', 'Final Review')], default='employment_type', max_length=50),
        ),
        migrations.CreateModel(
            name='ResponsibleLendingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disposable_income_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disposable_income_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('affordability_index_before', models.DecimalField(decimal_places=2, help_text='Percentage of income remaining before new loan.', max_digits=6)),
                ('affordability_index_after', models.DecimalField(decimal_places=2, help_text='Percentage of income remaining after new loan.', max_digits=6)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('existing_active_loans', models.PositiveIntegerField(default=0)),
                ('existing_monthly_commitments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('otp_verified', models.BooleanField(default=False)),
                ('documents_complete', models.BooleanField(default=False)),
                ('employment_verified', models.BooleanField(default=False)),
                ('income_verified', models.BooleanField(default=False)),
                ('kyc_passed', models.BooleanField(default=False)),
                ('aml_passed', models.BooleanField(default=False)),
                ('credit_bureau_checked', models.BooleanField(default=False)),
                ('sanctions_checked', models.BooleanField(default=False)),
                ('pep_checked', models.BooleanField(default=False)),
                ('fraud_flags', models.PositiveIntegerField(default=0)),
                ('previous_defaults', models.PositiveIntegerField(default=0)),
                ('previous_missed_payments', models.PositiveIntegerField(default=0)),
                ('previous_successful_loans', models.PositiveIntegerField(default=0)),
                ('borrower_score', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveIntegerField(default=100)),
                ('risk_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('conditional', 'Approve with Conditions'), ('decline', 'Decline')], max_length=20)),
                ('recommended_max_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision_reasons', models.JSONField(blank=True, default=list, help_text='Reasons generated by the Responsible Lending Engine.')),
                ('engine_version', models.CharField(default='1.0', max_length=20)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_lending_assessments', to='borrowers.borrowerprofile')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_lending_assessments', to='lenders.lenderprofile')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_lending_assessment', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Responsible Lending Assessment',
                'verbose_name_plural': 'Responsible Lending Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
