# Generated by Django 6.0.5 on 2026-08-08 13:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
        ('lenders', '0002_initial'),
        ('loans', '0003_alter_loanapplication_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsiblelendingassessment',
            options={'ordering': ['-assessed_at'], 'verbose_name': 'Affordability Assessment', 'verbose_name_plural': 'Affordability Assessments'},
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='affordability_index_before',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='aml_passed',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='borrower_score',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='credit_bureau_checked',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='decision_reasons',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='documents_complete',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='employment_verified',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='fraud_flags',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='income_verified',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='kyc_passed',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='otp_verified',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='pep_checked',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='previous_defaults',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='previous_missed_payments',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='previous_successful_loans',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='risk_category',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='responsiblelendingassessment',
            name='sanctions_checked',
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='advice',
            field=models.JSONField(blank=True, default=list, help_text='Plain-language recommendations for the borrower.'),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='installment_to_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='outcome',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('tight', 'Tight'), ('unaffordable', 'Unaffordable')], default='comfortable', max_length=20),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='recommended_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.CharField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_term',
            field=models.PositiveIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')], default=3),
        ),
        migrations.AlterField(
            model_name='responsiblelendingassessment',
            name='affordability_index_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of income remaining after the new loan.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='responsiblelendingassessment',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affordability_assessments', to='borrowers.borrowerprofile'),
        ),
        migrations.AlterField(
            model_name='responsiblelendingassessment',
            name='engine_version',
            field=models.CharField(default='2.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='responsiblelendingassessment',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affordability_assessments', to='lenders.lenderprofile'),
        ),
        migrations.AlterField(
            model_name='responsiblelendingassessment',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affordability_assessment', to='loans.loanapplication'),
        ),
    ]
