# Generated by Django 5.2.3 on 2025-06-25 10:03

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='pending_reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outstanding_docs', 'Outstanding documentation'), ('inconsistent_info', 'Inconsistent or mismatched information'), ('recent_activity', 'Recent application activity'), ('income_instability', 'Income instability or unclear source of funds'), ('kyc_checks', 'KYC/AML Compliance checks'), ('unverified_contact', 'Unverified contact details')], max_length=99),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='rejection_reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('low_credit_score', 'Low credit score'), ('job_instability', 'Unstable employment or job instability'), ('high_dti', 'High Debt-to-Income ratio'), ('insufficient_income', 'Insufficient income'), ('incomplete_docs', 'Incomplete or incorrect documentation (post 14 days pending)'), ('income_requirement_not_met', 'Income requirements not met'), ('high_existing_debts', 'High volume of Existing debts'), ('insufficient_credit_history', 'Insufficient credit history'), ('public_records', 'Items of public record'), ('multiple_loans', 'Multiple loan applications or Excessive loan take outs'), ('default_existing_loans', 'Default on existing loans')], max_length=205),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='status_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.CharField(choices=[(3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_term',
            field=models.PositiveIntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (24, '24 Months'), (36, '36 Months')], default=3),
        ),
    ]
