# Generated by Django 5.2.3 on 2025-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_pending_reasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='pending_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Reject'), ('approved', 'Approve')], default='pending', max_length=50),
        ),
    ]
