# Generated by Django 6.0.5 on 2026-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_responsiblelendingassessment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='expense_discrepancy_flag',
            field=models.BooleanField(default=False, help_text='Declared expenses appear well below observed spending.'),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='expenses_verified',
            field=models.BooleanField(default=False, help_text='True only if a statement was read and outflows were parsed.'),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='name_match_flag',
            field=models.BooleanField(default=False, help_text='Statement/ID name did not match the profile name.'),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='observed_outflows',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total outflows read from an uploaded statement, if any.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='responsiblelendingassessment',
            name='review_signals',
            field=models.JSONField(blank=True, default=list, help_text='Human-readable flags for lender review. Advisory, not a verdict.'),
        ),
    ]
