# Generated by Django 5.2.3 on 2025-06-26 05:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanapplication_pending_reasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='pending_reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outstanding_docs', 'Outstanding documentation'), ('inconsistent_info', 'Inconsistent or mismatched information'), ('recent_activity', 'Recent application activity'), ('income_instability', 'Income instability or unclear source of funds'), ('kyc_checks', 'KYC/AML Compliance checks'), ('unverified_contact', 'Unverified contact details')], max_length=99),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='rejection_reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('low_credit_score', 'Low credit score'), ('job_instability', 'Unstable employment or job instability'), ('high_dti', 'High Debt-to-Income ratio'), ('insufficient_income', 'Insufficient income'), ('incomplete_docs', 'Incomplete or incorrect documentation (post 14 days pending)'), ('income_requirement_not_met', 'Income requirements not met'), ('high_existing_debts', 'High volume of Existing debts'), ('insufficient_credit_history', 'Insufficient credit history'), ('public_records', 'Items of public record'), ('multiple_loans', 'Multiple loan applications or Excessive loan take outs'), ('default_existing_loans', 'Default on existing loans')], max_length=205),
        ),
    ]
