# Generated by Django 6.0.5 on 2026-08-10 13:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_responsiblelendingassessment_expense_discrepancy_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='pending_reasons',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outstanding_docs', 'Outstanding documentation'), ('inconsistent_info', 'Inconsistent or mismatched information'), ('recent_activity', 'Recent application activity'), ('income_instability', 'Income instability or unclear source of funds'), ('unverified_contact', 'Unverified contact details'), ('unverifiable_documentation', 'Expenses Self-declared (Unverifiable documents)')], max_length=115),
        ),
    ]
