# Generated by Django 6.0.5 on 2026-08-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_pending_reasons'),
    ]

    operations = [
    ]
