# Generated by Django 5.2.3 on 2025-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_pending_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
