# Generated by Django 6.0.5 on 2026-08-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20260811_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, help_text='Public loan reference, e.g. FGL-2026-B7Q4M9. Distinct from the application reference; linked via the application.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, help_text='Public reference, e.g. FG-2026-A3F9K2. Safe to share; the handle borrower and lender cite for any query or dispute.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='source',
            field=models.CharField(choices=[('app', 'Mobile App'), ('ussd', 'USSD'), ('web', 'Web')], default='web', max_length=20),
        ),
    ]
