# Generated by Django 6.0.5 on 2026-08-14 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_initial'),
        ('loans', '0008_loan_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['-date_paid']},
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='claimed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='external_reference',
            field=models.CharField(blank=True, help_text="The borrower's own transaction reference from the bank/mobile-money channel, if any.", max_length=120),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='flow',
            field=models.CharField(choices=[('external', 'External (paid outside the platform)'), ('gateway', 'Gateway (confirmed by payment rail)')], default='external', max_length=10),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='method',
            field=models.CharField(choices=[('bank', 'Bank transfer'), ('mpesa', 'M-Pesa'), ('ecocash', 'EcoCash'), ('cash', 'Cash'), ('gateway', 'In-app payment')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='proof',
            field=models.FileField(blank=True, help_text="Borrower's proof of payment (screenshot, statement, receipt).", null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed (awaiting lender confirmation)'), ('confirmed', 'Confirmed by lender'), ('rejected', 'Rejected (not received)'), ('disputed', 'Disputed')], default='claimed', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the borrower says the payment was made.'),
        ),
    ]
