# Generated by Django 6.0.5 on 2026-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loanpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('loan_application', 'Loan Application'), ('loan_payment', 'Loan Payment'), ('payment_update', 'Payment Update'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_update', 'Loan Update'), ('document_update', 'Documents Updated'), ('loan_deleted', 'Loan Deleted')], default='loan_application', max_length=20),
        ),
    ]
