# Generated by Django 6.0.5 on 2026-09-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_borrowergroup_activity_description_and_more'),
        ('loans', '0010_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Set when the applicant applied as a member of this group. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loan', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Set when the applicant applied as a member of this group. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loan_applications', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='group_data_consent',
            field=models.BooleanField(default=False),
        ),
    ]
