# Generated by Django 6.0.5 on 2026-09-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_borrowergroup_activity_description_and_more'),
        ('loans', '0011_loan_group_loanapplication_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Set when the loan is taken as a member of this group. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_loans', to='groups.borrowergroup'),
        ),
    ]
