# Generated by Django 6.0.5 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_alter_loan_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='current_stage',
            field=models.CharField(choices=[('employment_type', 'Employment Type'), ('documents', 'Upload Documents'), ('affordability', 'Affordability'), ('loan_calculator', 'Loan Calculator'), ('apply_loan', 'Submit Loan'), ('submitted', 'Final Review')], default='employment_type', max_length=50),
        ),
    ]
