# Generated by Django 6.0.5 on 2026-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_alter_loanapplication_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_status',
            field=models.CharField(blank=True, choices=[('pending_kfs', 'Awaiting borrower acknowledgement'), ('ready', 'Ready to disburse'), ('disbursed', 'Disbursed')], default='pending_kfs', max_length=16),
        ),
    ]
