# Generated by Django 6.0.5 on 2026-10-03 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0006_delete_keyfactsstatement'),
        ('loans', '0014_loan_disbursement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Carried from the application at approval. The KFS generator reads this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='lenders.lenderproduct'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='product',
            field=models.ForeignKey(blank=True, help_text="The product the borrower chose when applying. Drives the Key Facts Statement's fees. May be null for legacy lenders without products.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='lenders.lenderproduct'),
        ),
        migrations.CreateModel(
            name='KeyFactsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated — awaiting borrower acknowledgement'), ('borrower_ack', 'Borrower acknowledged — awaiting lender'), ('acknowledged', 'Fully acknowledged (locked)'), ('void', 'Void / superseded')], default='generated', max_length=16)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kfs_version', models.CharField(default='KFS v1.0', max_length=20)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kfs', to='loans.loan')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kfs_statements', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
