# Generated by Django 6.0.5 on 2026-05-22 16:41

import django.core.validators
import lenders.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenderDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('company_registration', 'Company Registration'), ('financial_statements', 'Financial Statements'), ('tax_clearance', 'Tax Clearance'), ('license_certificate', 'Borrowing License'), ('proof_of_address', 'Business Address Proof'), ('other', 'Other Supporting Documents')], max_length=50)),
                ('file', models.FileField(upload_to=lenders.models.upload_to_lender_docs)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('company_name', models.CharField(help_text='Registered company name', max_length=200, null=True)),
                ('trading_name', models.CharField(blank=True, help_text='Trading name if different from registered name', max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=50)),
                ('tax_identification_number', models.CharField(blank=True, help_text='Tax Identification Number (TIN)', max_length=50)),
                ('date_of_establishment', models.DateField(blank=True, help_text='Date company was established', null=True)),
                ('ownership_type', models.CharField(blank=True, choices=[('', 'Select...'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company'), ('corporation', 'Corporation'), ('cooperative', 'Cooperative'), ('ngo', 'Non-Governmental Organization')], default='', max_length=50)),
                ('business_email', models.EmailField(help_text='Primary business email address', max_length=254, null=True)),
                ('phone_number', models.CharField(help_text='Primary contact number', max_length=20, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.TextField(help_text='Physical office address')),
                ('city', models.CharField(default='Maseru', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('ceo_first_name', models.CharField(max_length=100, null=True)),
                ('ceo_last_name', models.CharField(max_length=100, null=True)),
                ('ceo_email', models.EmailField(blank=True, max_length=254)),
                ('ceo_phone', models.CharField(blank=True, max_length=20)),
                ('passport_photo', models.ImageField(blank=True, help_text='Upload a clear, passport-sized photograph.', null=True, upload_to=lenders.models.get_upload_path)),
                ('cbl_tier', models.CharField(blank=True, choices=[('', 'Not Determined'), ('tier1', 'Tier 1 - Deposit-Taking MFI'), ('tier2', 'Tier 2 - Credit-Only (Large, Assets ≥ M10M)'), ('tier3', 'Tier 3 - Credit-Only (Small, Assets < M10M)')], default='', help_text='CBL regulatory tier classification', max_length=20)),
                ('platform_tier', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('individual', 'Individual Lender (Platform)'), ('p2p', 'Peer-to-Peer (Platform Umbrella)')], default='', help_text='Platform classification for non-CBL-regulated lenders', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('documents_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('verified', 'Verified (Platform)'), ('cbl_pending', 'CBL Application Pending'), ('licensed', 'CBL Licensed'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('cbl_license_number', models.CharField(blank=True, help_text='CBL-issued license number', max_length=100)),
                ('cbl_license_expiry', models.DateField(blank=True, null=True)),
                ('operating_under_platform', models.BooleanField(default=False, help_text="Operating under platform's umbrella license")),
                ('stated_capital', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Declared capital in Maloti', max_digits=15, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total assets value', max_digits=15, null=True)),
                ('min_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('loan_terms', models.JSONField(blank=True, default=list, help_text='Available loan term options in months')),
                ('missed_payment_policy', models.CharField(choices=[('recalculate', 'Recalculate Interest on Skipped Payment'), ('standard', 'Standard Double Payment'), ('penalty', 'Apply Late Payment Penalty')], default='standard', max_length=20, null=True)),
                ('has_kyc_policy', models.BooleanField(default=False, help_text='Has implemented KYC policy')),
                ('has_aml_policy', models.BooleanField(default=False, help_text='Has implemented AML/CFT policy')),
                ('has_data_protection_policy', models.BooleanField(default=False, help_text='Has implemented data protection policy')),
                ('has_code_of_ethics', models.BooleanField(default=False, help_text='Has code of ethics/conduct')),
                ('has_complaints_procedure', models.BooleanField(default=False, help_text='Has consumer complaints procedure')),
                ('has_risk_management_policy', models.BooleanField(default=False, help_text='Has risk management framework')),
                ('participates_in_benchmarking', models.BooleanField(default=False, help_text='Participates in industry benchmarking')),
                ('submits_regulatory_reports', models.BooleanField(default=False, help_text='Submits required regulatory reports')),
                ('regulatory_body_name', models.CharField(blank=True, help_text='Name of regulatory body/association', max_length=200)),
                ('regulatory_body_membership_number', models.CharField(blank=True, max_length=100)),
                ('association_name', models.CharField(blank=True, help_text='Industry association membership', max_length=200)),
                ('association_membership_number', models.CharField(blank=True, max_length=100)),
                ('agrees_to_terms', models.BooleanField(default=False)),
                ('agrees_to_credit_conditions', models.BooleanField(default=False)),
                ('agrees_to_cbl_compliance', models.BooleanField(default=False)),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Lender Profile',
                'verbose_name_plural': 'Lender Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
