# Generated by Django 5.2.3 on 2025-09-17 16:29

import lenders.models
import micro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenderDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('company_registration', 'Company Registration'), ('financial_statements', 'Financial Statements'), ('tax_clearance', 'Tax Clearance'), ('license_certificate', 'Borrowing License'), ('proof_of_address', 'Business Address Proof'), ('other', 'Other Supporting Documents')], max_length=50)),
                ('file', models.FileField(upload_to=lenders.models.upload_to_lender_docs)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_first_name', models.CharField(max_length=20)),
                ('ceo_last_name', models.CharField(max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=micro.models.User)),
                ('company_name', models.CharField(default='', max_length=20)),
                ('registration_no', models.CharField(default='', max_length=20)),
                ('office_address', models.CharField(default='', max_length=100)),
                ('min_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('date_of_stablishment', models.CharField(default='', max_length=20)),
                ('business_email_ddress', models.CharField(default='', max_length=20)),
                ('ownership', models.CharField(choices=[(None, 'Select...'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Limited Liability Company', 'Limited Liability Company'), ('Corporation', 'Corporation')], default='', max_length=100)),
                ('licence_no', models.CharField(blank=True, default='', max_length=20)),
                ('regulatory_body_name', models.CharField(blank=True, default='', max_length=100)),
                ('regulatory_body_no', models.CharField(blank=True, default='', max_length=100)),
                ('kyc_policy_implementation', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('aml_policy_implementation', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('data_protection_policy_implementation', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('tax_number', models.CharField(default='', max_length=50)),
                ('code_of_ethics', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('association_name', models.CharField(default='', max_length=100)),
                ('membership_no', models.CharField(default='', max_length=20)),
                ('benchmarking', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('reporting', models.CharField(choices=[(None, 'Select...'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=100)),
                ('agrees_to_terms', models.BooleanField(default=False)),
                ('agrees_to_credit_conditions', models.BooleanField(default=False)),
                ('missed_payment_policy', models.CharField(choices=[('recalculate', 'Recalculate Interest on Skipped Payment'), ('standard', 'Standard Double Payment')], default='standard', help_text='How this lender handles missed payments.', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('licensed', 'Licensed')], default='unverified', max_length=20)),
                ('loan_terms', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
