# Generated by Django 5.2.3 on 2025-07-08 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lenderdocs',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile'),
        ),
    ]
