# Generated by Django 6.0.5 on 2026-05-22 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lenderdocs',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile'),
        ),
    ]
