# Generated by Django 5.1 on 2025-04-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='max_loan',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=50),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='min_loan',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=50),
        ),
    ]
