# Generated by Django 5.2.7 on 2025-12-23 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='business_email',
            field=models.EmailField(help_text='Primary business email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='ceo_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='ceo_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='company_name',
            field=models.CharField(help_text='Registered company name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='missed_payment_policy',
            field=models.CharField(choices=[('recalculate', 'Recalculate Interest on Skipped Payment'), ('standard', 'Standard Double Payment'), ('penalty', 'Apply Late Payment Penalty')], default='standard', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='phone_number',
            field=models.CharField(help_text='Primary contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
