# Generated by Django 5.1 on 2025-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_alter_lenderprofile_max_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='max_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='min_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50),
        ),
    ]
