# Generated by Django 5.2.3 on 2025-06-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='max_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='lenderprofile',
            name='min_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
