# Generated by Django 6.0.5 on 2026-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0003_lenderprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenderprofile',
            name='mobile_money_name',
        ),
        migrations.RemoveField(
            model_name='lenderprofile',
            name='mobile_money_number',
        ),
        migrations.RemoveField(
            model_name='lenderprofile',
            name='mobile_money_provider',
        ),
    ]
