# Generated by Django 5.2.3 on 2025-06-22 16:01

import django.db.models.deletion
import lenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0003_alter_lenderprofile_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('licensed', 'Licensed')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='LenderDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('company_registration', 'Company Registration'), ('financial_statements', 'Financial Statements'), ('tax_clearance', 'Tax Clearance'), ('license_certificate', 'Borrowing License'), ('proof_of_address', 'Business Address Proof'), ('other', 'Other Supporting Documents')], max_length=50)),
                ('file', models.FileField(upload_to=lenders.models.upload_to_lender_docs)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile')),
            ],
        ),
    ]
