# Generated by Django 5.2.7 on 2026-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0004_alter_lenderprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='operating_under_platform',
            field=models.BooleanField(default=False, help_text="Operating under platform's umbrella license"),
        ),
    ]
