# Generated by Django 6.0.5 on 2026-10-01 10:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0004_remove_lenderprofile_mobile_money_name_and_more'),
        ('loans', '0013_alter_loanapplication_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='cbl_licence_number',
            field=models.CharField(blank=True, help_text='CBL licence / registration number, e.g. CBL/MFI/XXXX/2026.', max_length=60),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='complaints_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='complaints_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='registered_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='registered_name',
            field=models.CharField(blank=True, help_text='Registered legal name, if different from the display/company name.', max_length=200),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='service_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='service_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='KeyFactsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated — awaiting borrower acknowledgement'), ('borrower_ack', 'Borrower acknowledged — awaiting lender'), ('acknowledged', 'Fully acknowledged (locked)'), ('void', 'Void / superseded')], default='generated', max_length=16)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kfs_version', models.CharField(default='KFS v1.0', max_length=20)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kfs', to='loans.loan')),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kfs_statements', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='LenderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard Personal Loan', max_length=120)),
                ('product_code', models.CharField(help_text='e.g. LP-STD-03', max_length=40)),
                ('version', models.CharField(blank=True, help_text='e.g. 03', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, help_text='Nominal annual interest rate, %.', max_digits=6)),
                ('interest_type', models.CharField(choices=[('flat', 'Flat'), ('reducing', 'Reducing balance')], default='flat', max_length=12)),
                ('interest_calculation_note', models.CharField(blank=True, help_text='Free-text description of how interest is calculated (shown on KFS).', max_length=200)),
                ('repayment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='monthly', max_length=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_term', models.PositiveIntegerField(blank=True, help_text='months', null=True)),
                ('max_term', models.PositiveIntegerField(blank=True, help_text='months', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lenders.lenderprofile')),
            ],
            options={
                'ordering': ['lender', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('initiation', 'Initiation Fee'), ('service', 'Service / Administration Fee'), ('credit_bureau', 'Credit Bureau Fee'), ('insurance', 'Insurance Premium'), ('late_payment', 'Late Payment Charge'), ('early_settlement', 'Early Settlement Charge'), ('restructuring', 'Restructuring Fee'), ('legal_recovery', 'Legal / Recovery Costs'), ('other', 'Other Charge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('basis', models.CharField(choices=[('once_origination', 'Once — at origination'), ('once_predisbursement', 'Once — before disbursement'), ('per_instalment', 'Per instalment'), ('per_occurrence', 'Per applicable occurrence'), ('as_incurred', 'As incurred'), ('conditional', 'If / when applicable'), ('na', 'Not applicable')], default='conditional', max_length=24)),
                ('applicable', models.BooleanField(default=True, help_text='Does this fee apply to this product?')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='lenders.lenderproduct')),
            ],
            options={
                'ordering': ['product', 'fee_type'],
            },
        ),
    ]
