# Generated by Django 6.0.5 on 2026-10-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0005_lenderprofile_cbl_licence_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyFactsStatement',
        ),
    ]
