# Generated by Django 5.2.3 on 2025-07-08 11:20

import borrowers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('id_proof', 'ID Proof'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('chief_letter', 'Chief Letter'), ('business_address', 'Business Address'), ('customer_invoice', 'Customer Invoice'), ('supplier_invoice', 'Suppliers Invoice'), ('business_registration', 'Business Registration Certificate'), ('tax_clearance', 'Tax Clearance Certificate'), ('business_statements', 'Business Financial Statements')], max_length=50, null=True)),
                ('file', models.FileField(upload_to=borrowers.models.upload_to)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], max_length=4, null=True)),
                ('date_of_birth', models.CharField(default='', max_length=20)),
                ('id_number', models.CharField(default='', max_length=30)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email_address', models.CharField(default='', max_length=100)),
                ('employer_name', models.CharField(default='', max_length=100)),
                ('employment_position', models.CharField(default='', max_length=100)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('position_level', models.CharField(blank=True, choices=[('entry-level', 'entry-level'), ('intermediate', 'intermediate'), ('senior-level', 'senior-level')], max_length=50, null=True)),
                ('home_address', models.CharField(default='', max_length=100)),
                ('employer_address', models.CharField(default='', max_length=100)),
                ('income_type', models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Wages', 'Wages'), ('Other', 'Other')], max_length=100, null=True)),
                ('pay_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month you usually receive your salary (1–31).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('monthly_expenses', models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Debt payment', 'Debt payment'), ('Insurence', 'Insurence'), ('Stokvel', 'Stokvel')], max_length=100, null=True)),
                ('existing_debts', models.CharField(blank=True, choices=[('Loans', 'Loans'), ('Credit Cards', 'Credit Cards'), ('Credit Accounts', 'Credit Accounts'), ('No Debts', 'No Debts')], max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed (Unregistered)'), ('registered_business', 'Registered Business')], max_length=20, null=True)),
                ('is_over_18', models.BooleanField(default=False)),
                ('agrees_to_terms', models.BooleanField(default=False)),
                ('agrees_to_credit_conditions', models.BooleanField(default=False)),
                ('information_consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
