# Generated by Django 5.1 on 2025-06-03 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerdocuments',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='borrowers.borrowerprofile'),
        ),
    ]
