# Generated by Django 5.1 on 2025-06-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_alter_borrowerdocuments_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowerdocuments',
            old_name='borrower',
            new_name='user',
        ),
    ]
