# Generated by Django 5.2.7 on 2025-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='employment_position',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='monthly_expenses',
        ),
        migrations.DeleteModel(
            name='GroupInvite',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
