# Generated by Django 5.2.3 on 2025-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerprofile',
            name='existing_debts',
            field=models.CharField(blank=True, choices=[('Loans', 'Loans'), ('Credit Cards', 'Credit Cards'), ('Credit Accounts', 'Credit Accounts'), ('No Debts', 'No Debts')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='income_type',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Wages', 'Wages'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='monthly_expenses',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Debt payment', 'Debt payment'), ('Insurence', 'Insurence'), ('Stokvel', 'Stokvel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='position_level',
            field=models.CharField(blank=True, choices=[('entry-level', 'entry-level'), ('intermediate', 'intermediate'), ('senior-level', 'senior-level')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], max_length=4, null=True),
        ),
    ]
