# Generated by Django 6.0.5 on 2026-09-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowerGroup',
        ),
    ]
