# Generated by Django 5.2.3 on 2025-07-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerprofile',
            name='existing_debts',
            field=models.CharField(blank=True, choices=[('Loans', 'Loans'), ('Credit Cards', 'Credit Cards'), ('Credit Accounts', 'Credit Accounts'), ('other', 'Other'), ('No Debts', 'No Debts')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='income_type',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Wages', 'Wages'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='monthly_expenses',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Debt payment', 'Debt payment'), ('Insurence', 'Insurence'), ('Stokvel', 'Stokvel'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='position_level',
            field=models.CharField(blank=True, choices=[('entry-level', 'Entry-level'), ('intermediate', 'Intermediate'), ('senior-level', 'Senior-level'), ('business-owner', 'Business owner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expenseanalysis',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='loans.loanapplication'),
        ),
    ]
