# Generated by Django 5.2.3 on 2025-06-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_alter_borrowerprofile_existing_debts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerdocs',
            name='document_type',
            field=models.CharField(blank=True, choices=[('id_proof', 'ID Proof'), ('bank_statement', 'Bank Statement'), ('payslip', 'Payslip'), ('chief_letter', 'Chief Letter'), ('business_address', 'Business Address'), ('customer_invoice', 'Customer Invoice'), ('supplier_invoice', 'Suppliers Invoice'), ('business_registration', 'Business Registration Certificate'), ('tax_clearance', 'Tax Clearance Certificate'), ('business_statements', 'Business Financial Statements')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed (Unregistered)'), ('registered_business', 'Registered Business')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrowerprofile')),
            ],
        ),
    ]
