# Generated by Django 6.0.5 on 2026-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_delete_borrowergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name the account is held under.', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='mobile_money_name',
            field=models.CharField(blank=True, help_text='Name registered on the mobile-money account.', max_length=200),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='mobile_money_number',
            field=models.CharField(blank=True, help_text='The number money is sent to.', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('', '—'), ('mpesa', 'M-Pesa'), ('ecocash', 'EcoCash')], max_length=20),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='payment_instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
