# Generated by Django 6.0.5 on 2026-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_borrowerprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='mobile_money_name',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='mobile_money_number',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='mobile_money_provider',
        ),
    ]
