# Generated by Django 5.2.3 on 2025-06-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_alter_borrowerdocs_document_type_and_more'),
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerdocs',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_documents', to='loans.loanapplication'),
        ),
    ]
