# Generated by Django 5.2.3 on 2025-07-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_alter_borrowerdocs_loan_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrowerprofile')),
            ],
        ),
    ]
