# Generated by Django 5.2.3 on 2025-07-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0007_borrowerotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='BorrowerOTP',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
