# Generated by Django 5.2.7 on 2025-12-11 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0003_initial'),
        ('groups', '0001_initial'),
        ('lenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_groups', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='sub_admins',
            field=models.ManyToManyField(blank=True, related_name='co_administered_groups', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupactivity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupconstitution',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='constitution', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='endorsed_by',
            field=models.ManyToManyField(blank=True, related_name='endorsements_given', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='join_request_approvals', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='existing_connection',
            field=models.ForeignKey(blank=True, help_text='Who in the group do you know?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_referrals', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='interviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='rejections',
            field=models.ManyToManyField(blank=True, related_name='join_request_rejections', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupmeeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmeeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='endorsed_by_group_members',
            field=models.ManyToManyField(blank=True, related_name='member_endorsements', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_members', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='grouptypespecificsettings',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_settings', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='lendergroupsubscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_subscriptions', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='lendergroupsubscription',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subscriptions', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='groups.groupmeeting'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupmembership'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'borrower')},
        ),
        migrations.AlterUniqueTogether(
            name='lendergroupsubscription',
            unique_together={('lender', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'member')},
        ),
    ]
