# Generated by Django 5.2.7 on 2025-10-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendergroupsubscription',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subscriptions', to='lenders.lenderprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'borrower')},
        ),
        migrations.AlterUniqueTogether(
            name='lendergroupsubscription',
            unique_together={('lender', 'group')},
        ),
    ]
