# Generated by Django 5.2.3 on 2025-09-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('groups', '0001_initial'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='invited_lenders',
            field=models.ManyToManyField(blank=True, related_name='subscribed_groups', to='lenders.lenderprofile'),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='sub_admins',
            field=models.ManyToManyField(blank=True, related_name='sub_admin_groups', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.borrowergroup'),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='groups.GroupMembership', to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrowerprofile'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.borrowergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('borrower', 'group')},
        ),
    ]
