# Generated by Django 5.2.7 on 2025-10-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowergroup',
            name='constitution',
        ),
        migrations.AddField(
            model_name='groupconstitution',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='constitution', to='groups.borrowergroup'),
        ),
    ]
