# Generated by Django 6.0.5 on 2026-09-02 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowergroup',
            name='activity_description',
            field=models.CharField(blank=True, help_text="Optional detail, e.g. 'Maize farmers, Leribe' or 'Maseru market traders'.", max_length=255),
        ),
        migrations.AddField(
            model_name='borrowergroup',
            name='economic_activity',
            field=models.CharField(choices=[('none', 'General savings (no shared activity)'), ('farming', 'Farming / agriculture'), ('trading', 'Trading / retail'), ('services', 'Services'), ('mixed', 'Mixed activities')], default='none', help_text="The group's shared economic activity, if any. Anchors future value-chain / merchant data. 'none' for general savings groups.", max_length=20),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='acting_until',
            field=models.DateTimeField(blank=True, help_text='If set, the current role is TEMPORARY and reverts to previous_role after this time. Null = permanent role.', null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='previous_role',
            field=models.CharField(blank=True, help_text='Role to revert to when an acting role expires.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='GroupContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('mpesa', 'M-Pesa'), ('ecocash', 'EcoCash'), ('cash', 'Cash'), ('gateway', 'In-app payment')], max_length=20)),
                ('status', models.CharField(choices=[('claimed', 'Claimed (awaiting confirmation)'), ('confirmed', 'Confirmed received'), ('rejected', 'Rejected (not received)')], default='claimed', max_length=10)),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('external_reference', models.CharField(blank=True, help_text="Member's own bank/mobile-money txn reference.", max_length=120)),
                ('proof', models.FileField(blank=True, null=True, upload_to='group_contribution_proofs/')),
                ('period_label', models.CharField(blank=True, help_text="e.g. '2026-08' or 'Cycle 3' — which period this covers.", max_length=40)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='The treasurer/admin membership who confirmed receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_confirmed', to='groups.groupmembership')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.borrowergroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='GroupFinancialRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected contribution per member per cycle.', max_digits=12, null=True)),
                ('contribution_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom / irregular')], default='monthly', max_length=20)),
                ('contribution_flexible', models.BooleanField(default=False, help_text='If true, members may contribute variable amounts (e.g. share-based savings groups).')),
                ('payout_type', models.CharField(choices=[('rotating', 'Rotating (ROSCA — each member takes the pot in turn)'), ('event_triggered', 'Event-triggered (e.g. burial society payout on a death)'), ('end_of_term', 'End-of-term (save through a cycle, share out at the end)'), ('internal_lending', 'Internal lending (pool is lent to members at interest)'), ('none', 'No structured payout')], default='rotating', max_length=20)),
                ('rotation_order', models.JSONField(blank=True, help_text='Ordered list of membership IDs for the payout rotation.', null=True)),
                ('current_rotation_index', models.PositiveIntegerField(default=0, help_text='Whose turn it is — index into rotation_order.')),
                ('cycle_number', models.PositiveIntegerField(default=1, help_text='Which full rotation the group is on.')),
                ('payout_per_event', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed payout amount when the trigger event occurs.', max_digits=12, null=True)),
                ('term_end_date', models.DateField(blank=True, help_text='When the cycle shares out.', null=True)),
                ('internal_interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest % on loans made from the pool.', max_digits=5, null=True)),
                ('payout_destination_note', models.CharField(blank=True, help_text="How/where the group holds its funds (e.g. 'Group bank account at X', 'Treasurer-managed mobile-money account'). Recorded, not held by the platform.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_rules', to='groups.borrowergroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kind', models.CharField(choices=[('rotation', 'Rotation payout (ROSCA)'), ('event', 'Event payout (e.g. burial)'), ('share_out', 'End-of-term share-out'), ('loan', 'Internal loan disbursement'), ('other', 'Other')], default='rotation', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (confirmed sent)'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('reference', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('cycle_number', models.PositiveIntegerField(blank=True, help_text='Rotation cycle this payout belongs to, if applicable.', null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_authorised', to='groups.groupmembership')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='groups.borrowergroup')),
                ('recipient', models.ForeignKey(blank=True, help_text='Member receiving the payout (blank for a group-external payout).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_received', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GroupTypeSpecificSettings',
        ),
    ]
