# Generated by Django 5.2.7 on 2025-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_borrowergroup_constitution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitation_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
