# Generated by Django 6.0.5 on 2026-09-07 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_delete_borrowergroup'),
        ('groups', '0003_borrowergroup_activity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_version', models.CharField(max_length=20)),
                ('given', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('physical_form', 'Signed physical form (assisted capture)'), ('digital', 'Digital agreement (self-service)'), ('verbal_witnessed', 'Verbal, witnessed')], max_length=20)),
                ('signed_form', models.FileField(blank=True, help_text='Scan/photo of the signed physical consent form.', null=True, upload_to='consent_forms/')),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='borrowers.borrowerprofile')),
                ('captured_by', models.ForeignKey(blank=True, help_text='The agent/sub-admin who captured this consent, if assisted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_captured', to='borrowers.borrowerprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['borrower', 'given', 'withdrawn'], name='groups_data_borrowe_560f0e_idx')],
            },
        ),
    ]
