# Generated by Django 5.2.7 on 2025-11-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
        ('groups', '0004_groupinvitation_invitee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitation_code',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to='borrowers.borrowerprofile'),
        ),
    ]
