# Generated by Django 6.0.5 on 2026-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_dataprocessingconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconstitution',
            name='document',
            field=models.FileField(blank=True, help_text="The group's written constitution, if they have one (scan, photo, or PDF). Optional — the structured fields below capture the same rules for the system.", null=True, upload_to='constitutions/'),
        ),
        migrations.AddField(
            model_name='groupconstitution',
            name='document_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
