# Generated by Django 5.2.7 on 2025-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupinvitation_invitation_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvitation',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Group Invitation', 'verbose_name_plural': 'Group Invitations'},
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='endorsements_required',
            field=models.IntegerField(default=0, help_text='Number of members who must endorse'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='expires_at',
            field=models.DateTimeField(help_text='Invitation expiry date'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitation_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitee_name',
            field=models.CharField(help_text='Full name of invitee', max_length=200),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='personal_message',
            field=models.TextField(blank=True, help_text='Optional message to invitee'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='reason_for_invite',
            field=models.TextField(blank=True, help_text='Why inviting this person'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='relationship',
            field=models.CharField(blank=True, help_text='Friend, Family, Colleague, etc.', max_length=100),
        ),
    ]
