# Generated by Django 5.2.7 on 2025-11-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_initial'),
        ('groups', '0006_alter_groupinvitation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='borrowers.borrowerprofile'),
        ),
    ]
