# Generated by Django 5.2.7 on 2025-11-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_alter_groupmembership_unique_together_and_more'),
        ('groups', '0008_groupactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='group_documents/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.borrowergroup')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.borrowerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
