# Generated by Django 5.2.7 on 2025-11-15 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_groupmeeting_meetingattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_promoted', 'Member Promoted'), ('member_demoted', 'Member Demoted'), ('role_changed', 'Role Changed'), ('meeting_created', 'Meeting Created'), ('meeting_updated', 'Meeting Updated'), ('meeting_deleted', 'Meeting Deleted'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('group_updated', 'Group Updated'), ('group_created', 'Group Created')], max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='groups.borrowergroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
