# Generated by Django 5.2.7 on 2026-02-17 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('NBSD', 'Non-Bank Supervision Department'), ('IISSD', 'Insurance, Institutions and Supervisions Division'), ('LEGAL', 'Legal Department')], max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to='regulator/signatures/')),
                ('is_active_reviewer', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=False, help_text='If true, this person can invite and manage other CBL staff.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
